server:
    port: 8087
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/

spring:
 application:
  name: ApiGateWayForService
 cloud:
    gateway:
      routes:
      - id: BookMyShow_JWTService
        uri: http://localhost:8081/
        predicates:
        - Path=/api/v1/**
      - id: BookMyShow_Admin_Service
        uri: http://localhost:8082/
        predicates:
        - Path=/api/v1/**
      - id: BookMyShow_User_Service
        uri: http://localhost:8084/
        predicates:
        - Path=/api/v1/**
          
      
  